server:
  port: 7878

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbs
    username: bonnie
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: ${MAIL_FROM_ADDRESS:no-reply@bbsltd.co.ke}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: bbs

sendgrid:
  api:
    key: ${SENDGRID_API_KEY}

