package com.bbs.bbsapi.enums

enum class ApprovalStage {
    MANAGING_DIRECTOR,
    TECHNICAL_DIRECTOR,
    SUBMITTED_TO_COUNTY,
    PENDING_COUNTY_FEE_PAYMENT,
    PENDING_CLIENT_COUNTY_FEE_PAYMENT,
    PENDING_COUNTY_APPROVAL,
    COUNTY_REJECTED_DOCUMENTS,
    APPROVED_BY_COUNTY
}