package com.bbs.bbsapi.enums

enum class FileType {
    ID,
    TITLE_DEED,
    KRA_PIN,
    REQUIREMENTS,
    SITE_VISIT_REPORT,
    ARCHITECTURAL_SKETCHES,
    WORKING_DRAWINGS,
    LAND_RATES,
    DEED_PLAN,
    SURVEY_MAP,
    SIGNED_AGREEMENT,
    PRELIMINARY,
    STRUCTURAL_ENGINEER_LICENSE,
    ARCHITECT_LICENSE,
    NCA_CONTRACTOR_LICENSE,
    COUNTY_INVOICE,
    COUNTY_RECEIPT,
    APPROVED_ARCHITECTURAL_DRAWINGS,
    APPROVED_STRUCTURAL_DESIGNS,
    CHANGE_OF_USE,
    CONTRACT_DOCUMENT,
    APPROVED_NCA_APPROVALS,
    APPROVED_NEMA_APPROVALS,
    PROGRESS_REPORT


}