package com.bbs.bbsapi.enums

enum class PreliminaryStatus {
    INITIATED, PENDING_T_D_APPROVAL, PENDING_M_D_APPROVAL, COMPLETE, PENDING_SUBMISSION_OF_FILES_TO_COUNTY, PENDING_APPROVAL_BY_COUNTY, PENDING_COUNTY_FEE_PAYMENT, PENDING_CLIENT_FACILITATION_PAYMENT, COUNTY_APPROVED_DOCUMENTS, COUNTY_REJECTED_DOCUMENTS
}